DATA SEGMENT 
	STR1 DB 10H DUP(?)
	COUNT DB 0  ;长度
DATA ENDS

CODE SEGMENT
		ASSUME DS:DATA,CS:CODE,ES:DATA
START:	MOV AX,DATA
		MOV DS,AX
		MOV SI,0
		MOV DI,0	
LOP1:   MOV AH,01H
		INT 21H
		CMP AL,0DH  ;判断是否是回车
		JZ L5
		CMP AL,20H  ;判断是否是空格
		JZ L4
		MOV STR1[SI],AL   ;存入字符串
		INC COUNT	
        INC SI		
L4:     LOOP LOP1
L5:		MOV CL,COUNT
		DEC SI
LOP2:   MOV DL,STR1[SI]   ;按相反顺序输出
		MOV AH,02H
		INT 21H
		DEC SI
		LOOP LOP2
		MOV AH,4CH
		INT 21H
CODE ENDS
	END START