DATA SEGMENT
    NUM1 DB 20H DUP(?)
	NUM11 DB 'please input the first number: $'
	NUM1L DB 0   ;数1的长度
	NUM22 DB 'please input the second number: $'
	NUM2 DB 20H DUP(?)
	NUM2L DB 0   ;数2的长度
	OUTPUT DB 'the output is: $' 
	CHOICE DB 'please input your choice: $'
DATA ENDS

STACK1 SEGMENT PARA STACK
	DW 20H DUP(0)
STACK1 ENDS

CODE SEGMENT 
	ASSUME CS:CODE,DS:DATA,SS:STACK1
START:  MOV AX,DATA
		MOV DS,AX
		MOV DX,OFFSET NUM11
		MOV AH,09H
		INT 21H
	    MOV SI,OFFSET NUM1
		CALL PROC_INPUT1
     	DEC SI
		MOV DL,0DH
		MOV AH,02H
		INT 21H
		MOV DL,0AH
		MOV DH,02H
		INT 21H
		MOV DX,OFFSET NUM22
		MOV AH,09H
		INT 21H
	    MOV DI,OFFSET NUM2
		CALL PROC_INPUT2 		
		DEC DI
		MOV DL,0DH
		MOV AH,02H
		INT 21H
		MOV DL,0AH
		MOV DH,02H
		INT 21H
		MOV DX,OFFSET CHOICE
		MOV AH,09H
		INT 21H
		MOV AH,21H
		INT 21H
		CMP AL,2BH
		JLE L+
		CMP AL,2DH
		JGE L-
		JMP NEXT
L+:		MOV DL,0DH       ;执行加法操作
		MOV AH,02H
		INT 21H
		MOV DL,0AH
		MOV DH,02H
		INT 21H
		MOV DX,OFFSET output
		MOV AH,09H
		INT 21H
        CALL PROC_PRITE+  
		JMP NEXT
J-:		MOV DL,0DH       ;执行减法操作
		MOV AH,02H
		INT 21H
		MOV DL,0AH
		MOV DH,02H
		INT 21H
		MOV DX,OFFSET output
		MOV AH,09H
		INT 21H
        CALL PROC_PRITE-
NEXT:   MOV AH,4CH
		INT 21H	
PROC_INPUT1 PROC
	MOV CX,1
INPUT1: MOV CL,4
        MOV AH,01H
		INT 21H
		CMP AL,39H
		JG RE1
		CMP AL,30H
		JL RE1
		SUB AL,30H
		SHL AL,CL
		XOR BL,BL
		MOV BL,AL
		MOV AH,01H
		INT 21H
		SUB AL,30H
		ADD BL,AL
		MOV [SI],BL
	    INC SI
		INC NUM1L
		LOOP INPUT1
RE1:	RET
PROC_INPUT1 ENDP

PROC_INPUT2 PROC
	MOV CX,1
INPUT2: MOV CL,4
        MOV AH,01H
		INT 21H
		CMP AL,39H
		JG RE2
		CMP AL,30H
		JL RE2
		SUB AL,30H
		SHL AL,CL
		MOV BL,AL
		MOV AH,01H
		INT 21H
		SUB AL,30H
		ADD BL,AL
		MOV [DI],BL
		INC DI
		INC NUM2L
		LOOP INPUT2
RE2:	RET	
PROC_INPUT2 ENDP

PROC_PRITE+ PROC
       	MOV AH,NUM1L
		MOV AL,NUM2L
		CMP AH,AL    ;比较两个数的长度
		JAE CHA      ;数num1长否
		XCHG SI,DI   ;交换首地址
		XCHG AH,AL   ;交换长度
CHA:    SUB AH,AL
        MOV BL,AH
		MOV CL,AL    ;相同长度数存在cl
		CLC          ;cf标志位送0  
LOP1:   MOV AL,[DI]  ;循环lop1为同长度部分相加 
		ADC [SI],AL
		DEC SI
		DEC DI
		LOOP LOP1
		MOV CL,BL    ;两数长度之差送cl
		JCXZ LLL     ;若两数长度相同，结束 
LOP2:   ADC BYTE PTR [SI],0  ;循环lop2处理剩余的字节
		DEC SI
		LOOP LOP2
LLL:    MOV CL,NUM1L	
LOP3:   PUSH CX
        INC SI
        MOV BL,[SI]
		MOV DL,[SI]
		MOV CL,4
		SHR DL,CL
		CMP DL,09H
		JG LA
		ADD DL,30H
		MOV AH,02H
		INT 21H
		JMP LB
LA:		ADD DL,37H
        MOV AH,02H
		INT 21H
LB:		MOV DL,BL
		AND DL,0FH
		CMP DL,09H
		JG LAA
		ADD DL,30H
		MOV AH,02H
		INT 21H
		JMP LBB
LAA:	ADD DL,37H
        MOV AH,02H
		INT 21
LBB:	POP CX
	    LOOP LOP3
        RET	
PROC_PRITE+ ENDP	

CODE ENDS
		END START